---
# vars file for tomcat
     req_tomcat_ver: 9.0.29
     tomcat_url: http://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-{{req_tomcat_ver.split('.')[0]}}/v{{req_tomcat_ver}}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz
     tomcat_port: 8080
