---
# tasks file for jenkins_install
- name: Download Jenkins
  become-user: tomcat
  get_url:
    url: "{{jenkins_url}}"
    dest: /opt/tomcat/latest/webapps

- name: Start tomcat
  systemd:
    state: started
    name: tomcat

- name: Wait for Tomcat to come up
  uri:
    url: "http://{{jenkins_ip}}:{{jenkins_port}}/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 200
  delay: 5

- name: Change jenkins config.xml users
  template:
    src: jenkins_config_and_users.xml
    dest: '/opt/tomcat/.jenkins/config.xml'

- name: Restart tomcat
  systemd:
    state: restarted
    name: tomcat

- name: Wait for Tomcat to come up
  uri:
    url: "http://{{jenkins_ip}}:{{jenkins_port}}/jenkins"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 200
  delay: 5
