---
      - name: Cleaning from previous versions
        file:
          path: '/opt/{{ item }}'
          state: absent
        loop:
          - apache-tomcat-*
          - tomcat
      
      - name: Create new group tomcat
        group:
          name: tomcat
          state: present

      - name: Create new user tomcat
        user:
          name: tomcat
          group: tomcat
          system: no
          shell: /bin/bash
          createhome: yes
          home: '/opt/tomcat'

      - name: Change own directory tomcat
        file:
          path: '/opt/tomcat'
          state: directory
          owner: root          

      - name: Downloading required tomcat
        get_url:
          url: "{{tomcat_url}}"
          dest: /opt

      - name: Extracting downloaded tomcat
        unarchive:
          src: '/opt/apache-tomcat-{{req_tomcat_ver}}.tar.gz'
          dest: '/opt'
          remote_src: yes
          
      - name: Renaming tomcat home
        shell: mv /opt/apache-tomcat-{{req_tomcat_ver}}/* /opt/tomcat

      - name: Change mode recurse conf
        file:
          path: '/opt/tomcat/conf'
          state: directory
          recurse: yes
          mode: g+r

      - name: Change mode conf
        file:
          path: '/opt/tomcat/conf'
          state: directory
          mode: g+x

      - name: Change group directory tomcat
        file:
          path: '/opt/tomcat/{{ item }}'
          state: directory
          recurse: yes
          owner: root
          group: tomcat
        loop:
          - lib
          - conf
          - bin
 
      - name: Change group file tomcat
        file:
          path: '/opt/tomcat/{{ item }}'
          state: file
          owner: root
          group: tomcat
        loop:
          - BUILDING.txt
          - CONTRIBUTING.md
          - LICENSE
          - NOTICE
          - README.md
          - RELEASE-NOTES
          - RUNNING.txt 

      - name: Configure tomcat.service
        template:
          src: tomcat.service
          dest: '/etc/systemd/system/'

      - name: Configure Service tomcat
        systemd:
          daemon_reload: yes
          daemon_reexec: yes

      - name: Start tomcat
        systemd:
          name: tomcat
          enabled: yes
          masked: no

      - name: Configure Tomcat users
        template: src=tomcat-users.xml dest='/opt/tomcat/conf/tomcat-users.xml'

      - name: Change tomcat users
        template: src=tomcat-users.xml dest='/opt/tomcat/conf/tomcat-users.xml'
        
      - name: Change tomcat port
        template: src=server.xml dest='/opt/tomcat/conf/server.xml'

      - name: Change manager context
        template: src=context_stock.xml dest='/opt/tomcat/webapps/manager/META-INF/context.xml'
  
      - name: Change host-manager context
        template: src=context_host.xml dest='/opt/tomcat/webapps/host-manager/META-INF/context.xml'

      - name: start tomcat
        shell: nohup /opt/tomcat/bin/startup.sh &

      - name: Tomcat /webapps ...
        file:
          path: '/opt/tomcat/{{ item }}'
          state: directory
          recurse: yes
          owner: tomcat
          group: tomcat
        loop:
          - webapps
          - work
          - temp
          - logs
